parameters:
#    pronc_rwesh.example.class: Pronc\RweshBundle\Example

services:
#    pronc_rwesh.example:
#        class: %pronc_rwesh.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
